project_eight/project_8/minerals/urls.py
from django.urls import path
from . import views

app_name = 'minerals'

urlpatterns = [
	path('', views.home, name="home"),
	path('detail/<int:id>/', views.detail, name="detail"),
	path('search/', views.search, name='search'),
    path('letter/<letter>/', views.letter, name='letter'),
    path('group/<group>/', views.group, name='group'),
    path('color/<color>/', views.color, name='color'),
]
 

project_eight/project_8/project_8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('', include('minerals.urls', namespace="minerals")),
    path('admin/', admin.site.urls),    
]
#for the django debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    SHOW_TOOLBAR_CALLBACK = True 

project_eight/project_8/minerals/models.py
from django.db import models

class Minerals(models.Model):
	"""fields detailing a mineral object"""
	name = models.CharField(default="", max_length=255)
	image_filename = models.CharField(default="", max_length=255)
	image_caption = models.CharField(default="", max_length=255)
	category = models.CharField(default="", max_length=255)
	formula = models.CharField(default="", max_length=255)
	strunz_classification = models.CharField(default="", max_length=255)
	crystal_system = models.CharField(default="", max_length=255)
	unit_cell = models.CharField(default="", max_length=255)
	color = models.CharField(default="", max_length=255)
	crystal_symmetry = models.CharField(default="", max_length=255)
	cleavage = models.CharField(default="", max_length=255)
	mohs_scale_hardness = models.CharField(default="", max_length=255)
	luster = models.CharField(default="", max_length=255)
	streak = models.CharField(default="", max_length=255)
	diaphaneity = models.CharField(default="", max_length=255)
	optical_properties = models.CharField(default="", max_length=255)
	group = models.CharField(default="", max_length=255)
	refractive_index = models.CharField(default="", max_length=255)
	crystal_habit = models.CharField(default="", max_length=255)
	specific_gravity = models.CharField(default="", max_length=255)

	def __str__(self):
		return 'Minerals - ' + self.name

project_eight/project_8/minerals/views.py
from django.shortcuts import render
from .models import Minerals 
from django.db.models import Q
 
def home(request):
    """the home page of the site. The 'A' anchor letter is 
    automatically selected """
    all_minerals = Minerals.objects.filter(name__startswith="A")
    clickable_L = "A"
    return render(request, 'index.html', {'all_minerals': all_minerals,
        'clickable_L': clickable_L})

def detail(request, id):
    """displays one single mineral """
    mineral = Minerals.objects.get(id=id)
    print("This is the mineral- {}".format(mineral))
    return render(request, 'detail.html', {'mineral': mineral})

def search(request):
    """activates when search field is used """
    term = request.GET.get('q')
    all_minerals = Minerals.objects.filter(
        Q(name__icontains=term)|Q(category__icontains=term)|
        Q(formula__icontains=term)|
        Q(strunz_classification__icontains=term)|
        Q(crystal_system__icontains=term)|Q(unit_cell__icontains=term)|
        Q(color__icontains=term)|Q(crystal_symmetry__icontains=term)|
        Q(cleavage__icontains=term)|
        Q(mohs_scale_hardness__icontains=term)|Q(luster__icontains=term)|
        Q(streak__icontains=term)|
        Q(diaphaneity__icontains=term)|Q(optical_properties__icontains=term)|
        Q(group__icontains=term)|
        Q(group__icontains=term)|Q(refractive_index__icontains=term)|
        Q(crystal_habit__icontains=term)|
        Q(specific_gravity__icontains=term))
    return render(request, 'index.html', {'all_minerals': all_minerals})

def letter(request, letter):
    """activates when a letter anchor is clicked """
    all_minerals = Minerals.objects.filter(name__startswith=letter)
    return render(request, 'index.html', {'all_minerals': all_minerals,
                                        'clickable_L': letter})

def group(request, group):
    """activates when a 'group' anchor is clicked"""
    all_minerals = Minerals.objects.filter(group=group)
    return render(request, 'index.html', {'all_minerals': all_minerals, 
                                    'clickable':group})

def color(request, color):
    """activates when a 'color' anchor is clicked """
    if color == 'other':
        colors = ["yellow", 'tan', 'white', 'gray', 'black', 'blue', 'violet']
        colors += ['brown', 'red', 'green', 'orange', 'other']
        all_minerals = Minerals.objects
        for i in colors:
            all_minerals = all_minerals.exclude(color__icontains=i)
    else:
        all_minerals = Minerals.objects.filter(color__icontains=color)
    return render(request, 'index.html', {'all_minerals': all_minerals,
                                        'clickable_C':color})

project_eight/project_8/minerals/templates/colors_clickables.html
{% for color in colors %}
	{% if clickable_C == color %}
    	<b><a class="bigger selectorC" 
    		href="">{{ color }}</a></b><br>
    {% else %}
    	<a class="selectorC" 
    	href="{% url 'minerals:color' color=color %}">{{ color }}</a><br>
	{% endif %}
{% endfor %}

project_eight/project_8/minerals/templates/detail.html
{% extends 'layout.html' %}
{% load clickables %}
{% load static %}

{% block body %}
  
    <div class="grid-100 mineral__container">
      <h1 id="ran_min" class="mineral__name">{{ mineral.name }}</h1>
      <div class="mineral__image-bg">
        {% with 'images/'|add:mineral.name|add:'.jpg' as image_static %}
        <img class="mineral__image" src="{% static image_static %}">
        {% endwith %}
        <p class="mineral__caption">{{ mineral.image_caption }}</p>
      </div>
      <div class="mineral__table-container">
        <table class="mineral__table">
          <tr>
            <td class="mineral__category">Category</td>
            <td>{{ mineral.category }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Formula</td>
            <td class="mineral__formula">{{ mineral.formula|safe }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Strunz Classification</td>
            <td>{{ mineral.strunz_classification }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Unit Cell</td>
            <td>{{ mineral.unit_cell }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Color</td>
            <td>{{ mineral.color }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Crystal Habit</td>
            <td>{{ mineral.crystal_habit }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Mohs Scale Hardness</td>
            <td>{{ mineral.mohs_scale_hardness }}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <div class="minerals__random">
    {% random_number %}
  </div>

{% endblock %}

project_eight/project_8/minerals/templates/groups_clickables.html
{% for group in groups %}
	{% if group == clickable %}
		<b><a class="bigger selectorG" 
			href="">{{ group }}</a></b><br>
	{% else %}
		<a class="selectorG" 
		href="{% url 'minerals:group' group=group %}">{{ group }}</a><br>
	{% endif %}
{% endfor %}

project_eight/project_8/minerals/templates/index.html
{% extends 'layout.html' %}
{% load clickables %}

{% block body %}
  
    <div class="grid-100">
      <ul class="minerals__container">
        {% for mineral in all_minerals %}
          <li class="minerals__item">
            <a class="minerals__anchor" 
        href="{% url 'minerals:detail' id=mineral.id %}">{{ mineral.name }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="minerals__random">
    <!--****** template tag below -->
      {% random_number %}
  </div>

{% endblock %}

project_eight/project_8/minerals/templates/layout.html
{% load staticfiles %}
{% load clickables %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Macky's Minerals: A magnificant catalog of minerals</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' 
  rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' 
  rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>

	<section id='colors' >
	<!--***** template tag below-->
		{% if clickable_C %}
    		{% colors_list clickable_C %}
    	{% else %}
    		{% colors_list %}
    	{% endif %}
		
    </section>

    <section id='groups' >
    <!--***** template tag below -->
    	{% if clickable %}
			{% groups_list clickable %}
		{% else %}
			{% groups_list %}
		{% endif %}
    	
	 </section>

<div class="bounds bounds--small">
    <div class="grid-100">
      <a href="index.html">
        <svg class="logo" viewBox="0 0 127.6 84.8" 
        preserveAspectRation="xMinYMin meet">
          <polygon 
        points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon 
class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon 
    points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,
    48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
       <a href="{% url 'minerals:home' %}">
        <h1 class="logo__name text-centered">Macky's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>
    </div>

    <section class="top-bar-right">
    	<form action="{% url 'minerals:search' %}" method="GET">
    		<ul class="menu">
    			<li><input id='searchbox' type="search" name="q"></li>
    			<li><input type="submit" value="Search"></li>
    		</ul>
    	</form>
    </section>

    <section id='letters'>
    <!--***** template tag below -->
    	{% if clickable_L %}
    		{% letters_list clickable_L %}
    	{% else %}
    		{% letters_list %}
    	{% endif %}
    </section>
    
{% block body %}
{% endblock %}

</body>

</html>

project_eight/project_8/minerals/templates/letters_clickables.html
{% for letter in letters %}
	{% if clickable_L == letter %}
    	<b><a class="bigger selectorL" href="">{{ letter }}</a></b>
    {% else %}
		<a class="selectorL" href="{% url 'minerals:letter' letter=letter %}">
		{{ letter }}</a>
	{% endif %}
{% endfor %} 

project_eight/project_8/minerals/templates/random_num.html
<a id="selectorR" class="minerals__anchor" 
href="{% url 'minerals:detail' id=random_num %}">Show random mineral</a>